import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className='bg-white dark:bg-[#191919] text-[#37352f] dark:text-[#ffffffcf]'
      >
        {children}
      </body>
    </html>
  );
}
